### PR TITLE
fix: typo: base.json

### PR DESCRIPTION
**Pull request by shaunie2fly**
typo : 'ponctually' to 'immediately' (I assume that's what its suppose to be ) ;)

### CODE REVIEW

**Comment by ansmonjol** [comment]
Hey @shaunie2fly, thanks for your suggestion :) You got it right 😄

**Review by ansmonjol — APPROVED** [review]

**Comment by ansmonjol** [comment]
I need to make some fix for the CI kobs to work on your PR

**Comment by ansmonjol** [comment]
Hey @shaunie2fly, can you rebase your branch with the latest version of lago-front please ?

**Comment by MorganeLecurieux** [comment]
Hello @shaunie2fly

**Comment by shaunie2fly** [comment]
Hi :) Should be in sync now.

**Comment by MorganeLecurieux** [comment]
Hi @shaunie2fly 
Sorry for the delay.
Actually we use a tool for translations and updated it after your comment so all you're requested changes are on the `main` branch right now.
So I'm closing this PR. Let me know if you encounter any problem :)

**Pull request closed without merging**
