### PR TITLE
misc: add missing KWD currency

### PR DESCRIPTION
**Pull request by lovrocolic**
## Context

This PR adds missing KWD currency

### CODE REVIEW

**Review by jdenquin — APPROVED** [review]

**Comment by ansmonjol** [comment]
This currency can have up to 3 decimal precision 

You should add it to the list of 3  precision currencies in src/core/serializers/serializeAmount.ts

**Review by ansmonjol — CHANGES_REQUESTED** [review]
This currency can have up to 3 decimal precision

You should add it to the list of 3 precision currencies in src/core/serializers/serializeAmount.ts

**Comment by michaelponrajah** [comment]
I think it's already mentioned [here](https://github.com/getlago/lago-front/blob/c8091cace463c13460cc888e8798e01a96902281/src/core/serializers/serializeAmount.ts#L4)

**Review by michaelponrajah — APPROVED** [review]

**Comment by lovrocolic** [comment]
> I think `KWD` is already mentioned [here](https://github.com/getlago/lago-front/blob/c8091cace463c13460cc888e8798e01a96902281/src/core/serializers/serializeAmount.ts#L4), line 4

yep, KWD has been included in the list from the start

**Pull request merged**
